create table "public"."field_schools" (
  "id"                   bigint  generated by default as identity not null,
  "program_name"         text    not null,
  "location"             text,
  "website_url"          text,
  "start_date"           date,
  "end_date"             date,
  "application_deadline" date,
  "cost"                 numeric,
  "season_year"          text,
  "organization"         text,
  "format"               text,
  "methods_taught"       text,
  "program_description"  text,
  "is_active"            boolean default false,
  constraint "field_schools_pkey" primary key (id)
);

alter table "public"."field_schools"
  enable row level security;

create policy "Allow public read access" on "public"."field_schools"
  for select
  to "anon"
  using (true);

grant maintain, references, select, trigger, truncate on table "public"."field_schools" to "anon";

grant maintain, references, trigger, truncate on table "public"."field_schools" to "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."field_schools" to "postgres";

grant maintain, references, trigger, truncate on table "public"."field_schools" to "service_role";

comment on column "public"."field_schools"."organization" is 'What is the University or Company running this field school';

comment on column "public"."field_schools"."start_date" is 'The date of the start of the field school';
