create table "public"."field_school_contacts" (
  "id"                      bigint generated by default as identity not null,
  "field_school_listing_id" bigint not null,
  "contact_email"           text   not null,
  constraint "field_school_contacts_pkey" primary key (id),
  constraint "field_school_contacts_field_school_listing_id_fkey" foreign key (field_school_listing_id) references public.field_schools(id) on delete cascade
);

alter table "public"."field_school_contacts"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."field_school_contacts" to "postgres";

grant maintain, references, trigger, truncate on table "public"."field_school_contacts" to "service_role";
