create table "public"."job_listings" (
  "id"              bigint  generated by default as identity (sequence NAME "public"."Job Listings_id_seq") not null,
  "title"           text,
  "company"         text,
  "state"           text,
  "employment_type" text,
  "salary_min"      numeric,
  "salary_max"      numeric,
  "salary_unit"     text,
  "description"     text,
  "apply_url"       text,
  "posted_date"     date,
  "company_website" text,
  "is_direct_post"  boolean,
  "posting_title"   text,
  constraint "Job Listings_pkey" primary key (id)
);

alter table "public"."job_listings"
  enable row level security;

alter table "public"."job_listings"
  add column "status" public.job_status;

create policy "Allow public read access" on "public"."job_listings"
  for select
  to "anon"
  using (true);

grant maintain, references, select, trigger, truncate on table "public"."job_listings" to "anon";

grant maintain, references, trigger, truncate on table "public"."job_listings" to "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."job_listings" to "postgres";

grant maintain, references, trigger, truncate on table "public"."job_listings" to "service_role";

comment on table "public"."job_listings" is 'This table is the master dataset for all created jobs';
