create table "public"."job_contacts" (
  "id"             bigint generated by default as identity not null,
  "job_listing_id" bigint not null,
  "contact_email"  text   not null,
  constraint "job_contacts_pkey" primary key (id)
);

alter table "public"."job_contacts"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."job_contacts" to "postgres";

grant maintain, references, trigger, truncate on table "public"."job_contacts" to "service_role";
