create table "public"."social_listings" (
  "id"                  bigint generated by default as identity not null,
  "name"                text   not null,
  "instagram_url"       text,
  "tiktok_url"          text,
  "youtube_url"         text,
  "x_url"               text,
  "podcast_url"         text,
  "website_url"         text,
  "primary_profile_url" text   not null,
  "content_focus"       text   not null,
  "channel_bio"         text   not null,
  "status"              text   not null default 'pending'::text,
  constraint "social_listings_pkey" primary key (id),
  constraint "social_listings_status_check" check ((status = ANY (ARRAY['pending'::text, 'approved'::text])))
);

alter table "public"."social_listings"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."social_listings" to "postgres";

grant maintain, references, trigger, truncate on table "public"."social_listings" to "service_role";
