create table "public"."social_contacts" (
  "id"                bigint generated by default as identity not null,
  "social_listing_id" bigint not null,
  "contact_email"     text   not null,
  constraint "social_contacts_pkey" primary key (id),
  constraint "social_contacts_social_listing_id_unique" unique (social_listing_id),
  constraint "social_contacts_social_listing_id_fkey" foreign key (social_listing_id) references public.social_listings(id) on delete cascade
);

alter table "public"."social_contacts"
  enable row level security;

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."social_contacts" to "postgres";

grant maintain, references, trigger, truncate on table "public"."social_contacts" to "service_role";
