create table "public"."submission_email_events" (
  "id"                bigint generated by default as identity not null,
  "submission_type"   text not null,
  "submission_id"     bigint not null,
  "display_name"      text not null,
  "contact_email"     text not null,
  "notification_data" jsonb not null default '{}'::jsonb,
  "delivery_status"   text not null default 'pending'::text,
  "attempt_count"     integer not null default 0,
  "resend_email_id"   text,
  "last_error"        text,
  "last_attempt_at"   timestamp with time zone,
  "sent_at"           timestamp with time zone,
  "created_at"        timestamp with time zone not null default now(),
  constraint "submission_email_events_pkey" primary key (id),
  constraint "submission_email_events_submission_unique" unique (submission_type, submission_id),
  constraint "submission_email_events_type_check" check (
    submission_type = any (array['job'::text, 'field_school'::text, 'social_listing'::text])
  ),
  constraint "submission_email_events_status_check" check (
    delivery_status = any (array['pending'::text, 'sent'::text, 'failed'::text])
  ),
  constraint "submission_email_events_attempt_count_check" check (attempt_count >= 0),
  constraint "submission_email_events_notification_data_check" check (jsonb_typeof(notification_data) = 'object'::text)
);

comment on table "public"."submission_email_events" is
  'Private outbox of public form submissions that require moderator email notifications.';

alter table "public"."submission_email_events"
  enable row level security;

revoke all on table "public"."submission_email_events" from public, "anon", "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update
  on table "public"."submission_email_events" to "postgres";

grant select, update
  on table "public"."submission_email_events" to "service_role";
