create table public.submission_email_events (
  id bigint generated by default as identity primary key,
  submission_type text not null
    check (submission_type in ('job', 'field_school', 'social_listing')),
  submission_id bigint not null,
  display_name text not null,
  contact_email text not null,
  notification_data jsonb not null default '{}'::jsonb
    check (jsonb_typeof(notification_data) = 'object'),
  delivery_status text not null default 'pending'
    check (delivery_status in ('pending', 'sent', 'failed')),
  attempt_count integer not null default 0
    check (attempt_count >= 0),
  resend_email_id text,
  last_error text,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  constraint submission_email_events_submission_unique
    unique (submission_type, submission_id)
);

comment on table public.submission_email_events is
  'Private outbox of public form submissions that require moderator email notifications.';

alter table public.submission_email_events enable row level security;

revoke all on table public.submission_email_events from public, anon, authenticated;

grant select, update on table public.submission_email_events to service_role;
